---

# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache and upgrade all packages (debian, etc)
      tags: always
      apt: 
        update_cache: yes 
        upgrade: yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

# run roles
- hosts: all
  tags: base
  become: true
  roles: 
     - base

- hosts: pvet
  tags: pvet
  become: true
  roles: 
     - pvet
    
- hosts: servert
  tags: servert
  become: true
  roles: 
     - servert

# end of run cleanup
- hosts: all
  tags: always
  become: true
  tasks:
  - name: cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: autoremove orphan packages (debian and ubuntu)
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
