---

# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Install software
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_utilities.yml
  
  # Perform remaining tasks:
  - import_tasks: system_setup/copy.yml
  - import_tasks: system_setup/packages.yml

  rescue:
    - set_fact: task_failed=true
