- block:
  - import_tasks: users/root.yml
#  - import_tasks: users/ansible.yml

  # Set up the ansible environment
#  - import_tasks: ansible_setup.yml
  
  # Perform remaining tasks:
#  - import_tasks: system_setup/cron.yml
#  - import_tasks: system_setup/copy.yml
#  - import_tasks: system_setup/packages.yml

  rescue:
    - set_fact: task_failed=true
