---

# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Install software
  - import_tasks: software/packages_cleanup.yml
    when: 
      - ansible_hostname != "pve0"
      - ansible_hostname != "pve1"
  - import_tasks: software/packages_utilities.yml
    when: 
      - ansible_hostname != "pve0"
      - ansible_hostname != "pve1"
  
  # Perform remaining tasks:
  - import_tasks: system_setup/cron.yml
    when: 
      - ansible_hostname != "pve0"
      - ansible_hostname != "pve1"
  - import_tasks: system_setup/copy.yml
    when: 
      - ansible_hostname != "pve0"
      - ansible_hostname != "pve1"
  - import_tasks: system_setup/packages.yml
    when: 
      - ansible_hostname != "pve0"
      - ansible_hostname != "pve1"

  rescue:
    - set_fact: task_failed=true
