---

- name: copy over .bashrc config files
  copy:
    src: files/.bashrc
    dest: /home/temhr/.bashrc
    owner: root
    group: root
    mode: 0644

- name: copy over .bash_prompt config files
  copy:
    src: files/.bash_prompt
    dest: /home/temhr/.bash_prompt
    owner: root
    group: root
    mode: 0644
