---

- name: copy over .bashrc config file
  copy:
    src: files/.bashrc
    dest: /home/temhr/.bashrc
    owner: root
    group: root
    mode: 0644

- name: copy over .bash_prompt config file
  copy:
    src: files/.bash_prompt
    dest: /home/temhr/.bash_prompt
    owner: root
    group: root
    mode: 0644

- name: copy over NTP config file
  copy:
    src: files/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
