- name: users | temhr | add sudoers file
  tags: settings,temhr,sudo,system,users
  copy:
    src: files/users/sudoers_temhr
    dest: /etc/sudoers.d/temhr
    owner: root
    group: root
    mode: 0440

- name: users | temhr | copy dotfiles
  copy:
    src: files/users/temhr/{{ item.src }}
    dest: /home/temhr/{{ item.dest}}
    owner: root
    group: root
    mode: 0644
  with_items:
      - { src: 'bash/.bashrc', dest: '.bashrc' }
      - { src: 'bash/.bash_aliases', dest: '.bash_aliases' }
      - { src: 'bash/.prompt', dest: '.prompt' }
  tags: dotfiles
