- name: users | temhr | add sudoers file
  tags: settings,temhr,sudo,system,users
  copy:
    src: files/users/sudoers_temhr
    dest: /etc/sudoers.d/temhr
    owner: root
    group: root
    mode: 0440
    
- name: .bashrc config file
  copy:
    src: files/users/bash/.bashrc
    dest: /home/temhr/.bashrc
    owner: root
    group: root
    mode: 0644

- name: .bash_aliases config file
  copy:
    src: files/users/bash/.bash_aliases
    dest: /home/temhr/.bash_aliases
    owner: root
    group: root
    mode: 0644

- name: .bash_prompt config file
  copy:
    src: files/users/bash/.bash_prompt
    dest: /home/temhr/.bash_prompt
    owner: root
    group: root
    mode: 0644
