---

# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  ## desktop environments
  - include_tasks: desktop_environments/gnome/packages.yml
    when: gnome is defined and gnome == true
  
  ## system setup
  #- import_tasks: system_setup/tweeks.yml
      
  ## uninstall software
  - import_tasks: software/packages_cleanup.yml
  
  ## install software
  - import_tasks: software/audacious.yml
  - import_tasks: software/audacity.yml
  - import_tasks: software/darktable.yml
  - import_tasks: software/firefox.yml
  - import_tasks: software/google_chrome.yml
  - import_tasks: software/kdenlive.yml
  - import_tasks: software/keepassxc.yml
  - import_tasks: software/libreoffice.yml
  - import_tasks: software/steam.yml
  - import_tasks: software/thunderbird.yml
  - import_tasks: software/vlc.yml

  rescue:
    - set_fact: task_failed=true
