---

- name: users | temhr | add sudoers file
  tags: settings,temhr,sudo,system,users
  copy:
    src: files/users/sudoers_temhr
    dest: /etc/sudoers.d/temhr
    owner: root
    group: root
    mode: 0440
    
- name: users | temhr | create config directories
  tags: dotfiles,temhr,tmux,users,vim
  file:
    path: /home/temhr/{{ item.dir }}
    state: directory
    owner: temhr
    group: temhr
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/plugins' }
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }

- name: users | temhr | copy dotfiles
  tags: dotfiles,users,temhr,htop,mc,vim
  copy:
    src: files/users/temhr/{{ item.src }}
    dest: /home/temhr/{{ item.dest }}
    owner: temhr
    group: temhr
    mode: 0600
  with_items:
    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash/bash_profile', dest: '.bash_profile' }
    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
    - { src: 'bash/bashrc', dest: '.bashrc' }
    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'mc/mc.ini', dest: '.config/mc/ini' }
    - { src: 'vim/vimrc', dest: '.vimrc' }
  
- name: users | temhr | copy vim color files
  tags: dotfiles,temhr,users,vim
  copy:
    src: users/temhr/vim/{{ item.src }}
    dest: /home/temhr/.vim/colors/{{ item.src }}
    owner: temhr
    group: temhr
    mode: 0600
  with_items:
    - { src: 'bubblegum-256-dark.vim' }
    - { src: 'darktango.vim' }
    - { src: 'jellybeans.vim' }
    - { src: 'xoria256.vim' }
    - { src: 'zenburn.vim' }
