---

- name: software | kdenlive | install package
  tags: packages,kdenlive,flatpak,workstation-packages
  become_user: temhr
  flatpak:
    name: org.kde.kdenlive
    method: user
    state: present
  when: kdenlive is defined and kdenlive == true
