---

# For Debian and Ubuntu, set up acceptance of steam license before continuing
- name: software | steam | accept license
  tags: gaming,steam
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"
  when:
    - ansible_distribution in ["Debian"]
    - steam is defined
    - steam == true

- name: software | steam | install package
  tags: steam,steam
  package:
    state: latest
    name: "{{ steam_package }}"
  when:
    - steam is defined
    - steam == true

- name: software | steam | install steam-devices package (debian)
  tags: steam,steam
  package:
    state: latest
    name: steam-devices
  when:
    - ansible_distribution in ["Debian"]
    - steam is defined
    - steam == true

- name: install vulkan drivers (debian)
  tags: drivers,steam
  package:
    state: latest
    name: mesa-vulkan-drivers
  when:
    - ansible_distribution in ["Debian"]
    - steam is defined
    - steam == true
