---

- name: gnome | packages | install flatpak support in gnome software
  tags: gnome,gnome-packages
  package:
    name:
    - gnome-software-plugin-flatpak
  when: ansible_distribution in ["Debian", "Ubuntu"]

# It appears as though Debian and Ubuntu place GNOME support for openvpn in a separate package
# This doesn't seem to be required in archlinux.
- name: gnome | packages | install gnome support for network-manager for debian and ubuntu hosts
  tags: gnome,gnome-packages,packages
  package:
    name:
      - network-manager-openvpn-gnome
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
