---

- name: users | root | create config directories
  file:
    path: /root/{{ item.dir }}
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
      - { dir: '.vim' }
      - { dir: '.vim/colors' }
  tags: dotfiles

- name: users | root | copy dotfiles
  tags: dotfiles,users,root
  copy:
    src: files/users/root/bash/{{ item.src }}
    dest: /root/{{ item.dest }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'bashrc', dest: '.bashrc' }
    - { src: 'bash_profile', dest: '.bash_profile' }
    - { src: 'profile', dest: '.profile' }
