# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/root.yml
  - import_tasks: users/ansible.yml
  - import_tasks: users/temhr.yml
    when: "'pve' not in group_names"

  # Set up the ansible environment
  - import_tasks: ansible_setup.yml

  # Install software
  - import_tasks: software/repositories.yml
    when: "'pve' not in group_names"
  - import_tasks: software/packages_cleanup.yml
    when: "'pve' not in group_names"
  - import_tasks: software/packages_utilities.yml
    when: "'pve' not in group_names"
  
  # Perform remaining tasks:
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/packages.yml
    when: "'pve' not in group_names"
  - import_tasks: system_setup/copy.yml

  rescue:
    - set_fact: task_failed=true
