---

- name: system setup | copy | NTP config file
  tags: copy,NTP,config
  copy:
    src: files/system_setup/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
