- name: Copy busybox httpd service file to appropriate folder
  copy:
    content: |
      [Unit]
      Description=Busybox HTTPD Server
      After=network.target #start after network is up

      [Service]
      Type=simple
      ExecStart=/usr/sbin/httpd -f -h ~/Sync/www -p 8080 -vvv

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/busybox-httpd.service.d/
    mode: '0644'
- name: Enable busybox httpd service at startup
  systemd:
    name: busybox-httpd.service
    enabled: yes
