---

- name: users | root | copy Bash files
  tags: bashfiles,users,root,bash,users
  copy:
    src: files/bash/{{ item.src }}
    dest: /root/{{ item.dest }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'bs.sh', dest: 'Sync/www/bs.sh' }
    - { src: 'prep-newguest.sh', dest: 'Sync/www/prep-newguest.sh' }
    - { src: 'prep-pve0.sh', dest: 'Sync/www/pve0-bs.sh' }
    - { src: 'prep-pve1.sh', dest: 'Sync/www/pve1-bs.sh' }
