---

- name: users | root | copy bash scripts
  tags: bashscripts,users,root,bash,users
  copy:
    src: files/bash/{{ item.src }}
    dest: /root/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'bs.sh', dest: 'Sync/www/bs.sh' }
    - { src: 'prep-newguest.sh', dest: 'Sync/www/prep-newguest.sh' }
    - { src: 'pve-bb.sh', dest: 'Sync/www/pve-bb.sh' }
    - { src: 'pve0-bs.sh', dest: 'Sync/www/pve0-bs.sh' }
    - { src: 'pve0-install.sh', dest: 'Sync/www/pve0-install.sh' }
    - { src: 'pve0_driver-nvidia.conf', dest: 'Sync/www/pve0_driver-nvidia.conf' }
    - { src: 'pve1-bs.sh', dest: 'Sync/www/pve1-bs.sh' }
